#!/usr/bin/env bash


# Runs your tests.
#
# Installation:
#
# 1. Place this file in your plugin's test/ directory.
# 2. Replace YOUR_PLUGIN (below) with the appropriate filename.
# 3. Set any options you need with additional `--cmd '...'` lines below.
#
# Usage:
#
# ./test     - runs all tests
# ./test foo - runs all tests whose names match foo


VIM="/Applications/MacVim.app/Contents/MacOS/Vim -v"

# Source the matchit plugin because it always will be sourced
# in actual use.
$VIM -u NONE -U NONE -N                      \
  --cmd 'set rtp+=../'                       \
  --cmd 'runtime macros/matchit.vim'         \
  --cmd 'source ../plugin/matchquote.vim'    \
  -S runner.vim                              \
  test_*.vim                                 \
  $*

cat messages.log

grep -q "0 errors, 0 failures" messages.log
status=$?
rm messages.log
exit $status

